### ISSUE TITLE
Create an install.bat

### ISSUE THREAD

**Issue by bobbydilley** [OfficialKingJulian/Useful-Batch#3]
You should have a batch file which will install the files to your C:\Windows directory so they can all be run. You could also have an uninstall.bat file that gets copied over as well, to uninstall all of the files.

useful-install.bat and useful-uninstall.bat could be good names so that they don't interfere with anything else.

**Comment by OfficialKingJulian** [comment]
Thanks for the feature suggestion! The file has been created and should work, instructions in the README
